version: '3.4'

services:
  producer:
    depends_on: 
     - rabbitmq
    image: ${DOCKER_REGISTRY-}rabbitproducer
    build:
      context: .
      dockerfile: Rabbit.Producer/Dockerfile
  

  consumer:
    depends_on: 
     - rabbitmq
    image: ${DOCKER_REGISTRY-}rabbitconsumer
    build:
      context: .
      dockerfile: Rabbit.Consumer/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

